// Joke text keyed by jokeKey. PLACEHOLDERS: the owner writes the final lines.
export const COPY: Record<string, string> = {
  "base.human": "[joke: you, one (1) human, converted at the going rate]",
  "food.chicken": "[joke: the chicken filed a complaint]",
  "food.beef": "[joke: steak, priced per cow]",
  "food.pork": "[joke: pork, priced per pig]",
  "food.fish": "[joke: fish, priced per fish]",
  "food.shrimp": "[joke: you ate the constituency]",
  "food.vegan": "[joke: vegan credit, grudgingly issued]",
  "food.other": "[joke: this food has no moral weight yet]",
  "pet.cat": "[joke: cats, apex insect predators, counted as dependants]",
  "pet.dog": "[joke: dogs, counted as dependants]",
  "pet.other": "[joke: unusual pet, weighed anyway]",
  "animal.mention": "[joke: you named an animal; the soldiers noticed]",
  "donation.givewell": "[joke: human lives, converted to insects]",
  "donation.shrimp": "[joke: SAVE THE SHRIMPS!]",
  "donation.chicken": "[joke: chickens helped]",
  "donation.fish": "[joke: fish helped]",
  "donation.insect": "[joke: BUG LIVES MATTER!]",
  "donation.orphan": "[joke: money given to no one we can price]",
  "charity.unrated": "[joke: not on the list; zero insects]",
  "charity.nodonation": "[joke: admired, not funded]",
  "money.hoarded": "[joke: all that revenue, and not one shrimp]",
  "ailab.doomer": "[joke: works at the lab, fears the lab]",
  "ailab.accel": "[joke: works at the lab, loves the lab]",
  "ailab.argue": "[joke: the soldiers argue about your employer]",
  "ailab.unknown": "[joke: AI lab, unpriced]",
  "employer.generic": "[joke: employer, morally neutral for now]",
  "job.generic": "[joke: job title noted]",
  "city.generic": "[joke: city noted]",
  "hobby.generic": "[joke: hobby noted]",
  "jev.skittles.yes": "[joke: would give up the Skittles]",
  "jev.skittles.no": "[joke: keeps the Skittles]",
  "jev.skittles.argue": "[joke: the soldiers argue over the Skittles]",
  "soldier.bugs.yes": "BUG LIVES MATTER! [placeholder: approves]",
  "soldier.bugs.no": "BUG LIVES MATTER! [placeholder: disapproves]",
  "soldier.bugs.argue": "BUG LIVES MATTER?! [placeholder: argues]",
  "soldier.shrimps.yes": "SAVE THE SHRIMPS! [placeholder: approves]",
  "soldier.shrimps.no": "SAVE THE SHRIMPS! [placeholder: disapproves]",
  "soldier.shrimps.argue": "SAVE THE SHRIMPS?! [placeholder: argues]",
};

export const joke = (key: string) => COPY[key] ?? `[joke: ${key}]`;
